function load_example() {
    $('#checkbox').prop('checked', false).change()
    var example_msa=">Sp030\nAGTGAGCCAATCCAAAGACTCAACATGTGAGGAAACCGTAGCCGATGGAATAACCGCCAATAGTCGGAGCGAAGCCTTGAATCTTACGCAGTTTCGCAGATCACAAGGGGCCACACTTACTTGTAGCAACCCGATCTTCGCCACTATCAAGATAAGGTACTGCGAGAGGGGGTCCAATGCTTCCGCTTTGCGCAGTAGCTTAGTCGCAGACGAAAGTCAGGGTCGTGATGCTCCTGGGGCTCTGAGCCTCCGAGTAATTGATGAATCCTGAATCGCGGGCTACGGGCGCTCTGGTCGGGGACACAGCGCTTGGGAAAAGCGCGGTTCCTACCGGCCCGACGAGGGCAGGGAGTAAACGAATTCATAGCGTCACTCAATTGACCGGACTGCATTATACTCCATTCGCTGTTGTCAGTTGTGTTGCAGGTAACGCGCAGCCACATGACCGATCAGGGAAGTAACCGAGCCTTAAATGAGGTTGATTTCCGGGGAGAGCCATCTGGGTATTAAGAGGCTGTAGACTTCAAATGCGCCGAAACAGTAGCTAGCGCTCCCTATTAAGTGTCTTACTCCTATCATTTAGAACCCCAGGCCTAGGCTAGCCCCAATCTATAGATGCATGTGTAGCCAAAACCGATTTGGGGCACCAATGGCTTGTCCGGTTTATCCAACTATAGCATACTTGGTCTCGCCTTATTGTGAGGCACTGACGATCGGTCCGTTGATGACCTAGCGGGCAGTCAAACGGCGAACGCTGACAACGCGTGGCTGGAGGATCAACCCCCGGACCATAAATCGCTGCAGTTGCTCTTCTCTTACAGAGTCAACTAGTACCGCTCCTCGCCAGATCAGTAGCTTCGACGGCCCGTTGACGCATACTACGGCATACCTACGCCTAAGCCGTACCTGACATTCAGACGAGTGAGCGACGACGGGTCGTAAAAGGATGCGCCACCTAGATTCATGGTGGACATGTGACTGAAGAGACTCATAACTGCGCGTGGCACTCTCATGGCACCGCAAAGGGAGTACGCTCTGACCGGCGACTATTCAGCGCATACTTCGTCAGAGGGCCTCCATAGTAGC\n>Sp031\nAGCGAGCCAATCCAAAGACACAACATGTGAGGAAACCGTAGCCGATGGAATAACCGACAATCGTCGATGCGAAGCCTTGAATCTTACGCAGTTTCGGAGATCGCAAGGGGCCACACTTACTTGTAGCAACGCGATCTACGCCACTATCAAGAAAAGGTTCTGCAGGAGGGGGCCCAATGCTTCCGCTTTGCGCAGTAGCTTAGTCGCAGACGCAAGTCGGGGTCGTGATGCTCCTCGAGCTCTGGGCCTCCGAGTAATTAATGAATCCTGAATCGCGGGCTAAGGGCGCTCTGGTCGGGGACGCAGCGCTTGGGAAAAGCGCGGTTGCTGCCGGACTGACGAGGGCAAGGAGTAAACGAATTCATGGCGTCACTCAATTGACCGGACTGCATTATACTCCATTCGCTGTTGTCAATTGGGTCGCAGGTAACGCGCAGCCACATGACCGATTAGGGAAGTAACTGAGCCTTAAATGAGGCTGATTTCCGGGGAAAGCCATCTGGGTATTAAGAGGCTGCAGACTTCAAATGCGCCGAAACAGTAGCTAGCGCTCCCTATTAAGTGCCTTACTCCTACCATTTAGACCCCCAGGCCTAGGCTAGCCCCAATCTATAGATGCATGTGTAGCCAAAACCGATTTGGGGCACCAATGGCTTGTCCGGTTTATCCAACTCTAGCATAATCGGTCTCGTTCTATCGTGAGGCACTGACGATCGGTCCGTTGATGACCTAGCGGGCAGTCAAACGGCGAATGCTAACAACGCGTGGCTGGAGGATCAACCCCCGGACCATAAATCGCGGCAGTTGCTCTTCTCTTTCAGAGTCAACTAGTACCGCTCCTCGCCAGATCAGTAGCTCCGACGGCCCCTTGACGCATATTACGGCAGACCTACGCCTAAGCCGCACCTAACATTCAGACGAGTGAGCAACAACGGGTCGTGAAAGGATGCGCCACCTAGATTCATGGTGGACATGTGATTAAAGCCACTCATAACTGCGTGTGGTAGTCTCATGGCACCACAAAGGGAGTACGCTCGGACCGGCAACTATTCAGCGCATACTTCGTCAGAGGGCCTCCACAGTAGC\n>Sp032\nAACGAGCATTGCCAGGGACATAACGTACTACTGAATCCTAGCATATGAAATGTGGGACAAGGATCTATACGAAGCCACGAACAATATTCGGTTCCCTACAGCATAAGGGGGCACGTGGGGTTGGTGCTGTACGATCGCCGACACCATGAAGGCAATTCCCAGCACGATGGAGCCCATTGCTTTTGCTTTGCGCCGTAATTTAGCCGCGAACGCACGTCTGGGTCGTGATGTTCTTTGCACAAAGCGCCTTCGAATGATCGATGTCTCCTGAAGCGCGGGCTTGGTGGACTCCGGCCGGGAACTCACCGTTCGGGTAAACCGCGGGTTACCCCTGGCTGATTACGGACGGGAGATTAAGAACGTATCGGGATACACGACTGCTCGAACCGAAGGCTAACGCATCCACTGTTGTTATTGTGGTCCTGGGTAGCGTCCGGCCACGTGACCGATTGCCACAGTGACAGAGCCCTTAATAATGCTGTTTTCCGGGAAGAGCCACCTGGGTATTAAGAGATTGCTAAGTTCGAATGCCCCGCAAAAGTTTCTACTGCTCCCGCATGAGGACCTTACTGATACCGTTCGAAGTGCCAGAGCCGGGGTCGTACCAGTCTCTAAGTCCGTCTGTCGCCACAACGACAATGGGGCAGTCGTTGCTTGTCCCGTCTATGCGTCTATATCGTAATGCGTTAGGAGATGTAGTGCGACGCGGACGATCGCACGGTCGTCTGCTAAACCGTTCATCGAACAGCGACTGTTCGCCACGCGCGGCTAGAGGATCAAAACCCGGACGATGAATCGCGGAAGTGGGTCCTCTATTAGATACTCAACTAGTACTGTCTCTGGCCGGATAAATGCCTCCAACAACGCGTTGAAGCACCTTGCGGCATACGCCCCTCTAGGCTTAGTCTAATATTTAGACAAGCGAGCATCGGCGAGTCGTGAGAGAACTGGGCACATGGATTGTTAGTGCATATGTTTCTAAGGACATGCATACCTGCGAGTGCCACTCTTATGGTTCCACAAAGGGAGTGCAGCGGGACCGACCACTTCCCAACGACCACCCTATCAGCAGGTGAGCAGAGTAGC\n>Sp000\nAGTGAGCGAGTCCAGAAACAGAATGGCTCGGGAAATCGTGGCCGATGAAATAGGCGACAACTGTCTGTACGAATCCTTAAACTATACGCGGTTCCCCACAGCCCAAGGGGTCCCGTTGGGTTGTTGCGATACGATTTACGTCACAATCAAGCTAATGATAAGCGCGCGTGGGACCAATGCTCTCGGTTCGCACTGCAGCTCAGCCTCGGGCGCGAGTCGGGGTCGTGATGTTCTTCGCGCATAACGCCTCCGACTGATCGATGCCTCCTGAATCACGGACTAAGGGCACTCTGGCCGGGGACGCACCGTCTGGGCAAAGTACGGTTGCAGCTGGGCCGACGATGGGAAGGAACACACGAATTGATCGTGGTACGCGATTGATCGAACTGAAGCATAACCCATACGCCGTTGTAACTTGGGTTGTGGGTAGCGAGCAGCGACGCGAGCATTTATGGCGGTGACAGAGCCTTCAATGAAAATGATTTGCAGGGAAAGCCATCTGGGCATTAAGAGACTGCGAACTCCACATGCGACGAAAAAGTTGCCACCGCTCCCTAGTAAGTATCTCACTGTTACCTTTTAAAGCGCAAGATCTAGACTAGCCCCAATCTGTTGGTGCGTTCGTAACCAAAATAAGATTGGGGCACCAATGGCCCGTCCAGTCTATGCGAGTATAGTATAATCGGTCACTTCATATTGTGCCACGCGGACGATCGTTCCGTCACCGGCTAAGCCGCCCCTCAAACTGCGACCGTTCGCAGAGCGTGGCTAGAGGATCAATATCCAGACCATGAATCGCGGGCGTCGTTCTTCTGTTTCACACTCAACTAGTATTGTCCCTTGTCGGATAAGCGACTCCGACGGCCCATTGATGCATGTTACGGCAGACTGCCAACTAAGCCCAGCCTAACACTGAAACGAGTGAGCAACAGCGAGCCGTATAAGGATGCGACACTTAGAGCCATAATGTACATGTTACTGACGGCACCCATATCTACGTGTGCCAATCTTATGGTTCCCCAAAGGAGGTACAGTCGGACCGGCAACTCCTGAGCGCCTGCTTCGTAAGAGGATCTTCACAGTAGC\n>Sp001\nAGTGAGCGAGTCCAGAAACAGAATGGCTCGGGAAATCGTGGCCGATGAAATTAGTGACAACTGTCTTTACGAATCCTTAAACTATACGCGGTTCCCCACAGCCCAAGGGGTCTCGTCGGGTTGTTGCGATACGATCTACGGCACAATAAGGTTAATGATAAGCGCGCGTGGGACCAATGCTCTCGGTTCGCACTGCAGCTCAGCCTCGGGCGTGAGTCCGGGTCGTGATGTTCTTCGCGCATATCGCCTCCGACTGATCGTTGCCTCCTGAGTCACGGACTAAGGGCACTCTGGCCGGGGACGCACCGTCTGGGCAAAGTACGGTTGCAGCTAGGCCGACCATGGGAAGGAACACACGAATTGATCGTGGTACGCGATTGATCGAACTGAAGCATAACCCATACGCCGTTGTAGCTTGGGTTGTGGGTAGCGAGCAGCGACGCAAGCAATTATGGCGGTGACAGAGCCTTCAATGAAAAGGATTTGCTGGGAAAGCTATCTGGGTATTAAGAGACTGCGAACTCCACATGCGACGAAAAAGTTGCCACGGCTCCCTAGTAAGTATCTCACTGTTACCTTTTAAAGCGCGAGATCTAGACTAGCCCCAATCTGTGGGTGCGTTCGTGACCAAAATAAGATTGGGACACCAATGGCCCGTCCAGTCTACGCGGCTATAGTATAATCGGTTATATAATATTGTACCACGCGGACGATCGTTCCGTCACCGGCTAAGCCGCCCCTCAAACTGCGACCGTTTGCAGAGCGTGGCTAGAGGATTAATATCCAGACCATGAATCGCGGGAGTCGTTCTTCTGTTTCACATTCAACTAGTATTGTCCCTTGTCAGATAAGCGACTCCGACGGCCCATTGATGCATGTTACGACAGACTGCCAACTAAGCCCAGCCTAACACGGAAACGAGTGAGCAACAGCGAGCCGTTTAAGTTTGCGACACTTAGAGCCATAATGTACATGTAACTGAGGGCACTCATATCTACGTGTGCCAAGCTTATGGTTCCTCAAAGGAGGTACAGTCGGACCGGCAACTCCTGAGCGCCTGCTTCGTGAGAGGATCTTCACAGTAGC\n>Sp029\nAGTGAGCGTGACCAGAAACATAAAGGTCTGGCAAATCATGGCCGATGAAATATGGGACAACTGTCTCTGCGAAACTTTAAGCTATAACCGGTTTACCAGAACGCAAGGGGGCACGTTGGATTGCTGCGATGCAATCTACGTCACAATCAAGTCAACGCTTAGCGCAAACGGGACCAATGCTCTCGCATTGCACAGTAGCTCAGCCGCGGGCGCAACTCAGGGTCGTGATGTTCTTGGTGCATAACGCCTCCGAGTGATCGGTGTCTCCTGAAACACCGACTCCGGGCGCTCCGGTTGGGGACGCACCGGCTAGTCAAAGTGCGGTTACAGCCTGACCAACCATTCAGGGGAGCACACGAATTGATCGTGGTTCACGATTCATCGAACCGAAGCGTAACCCATCCGCGGTTGAATCTTAGGTTATGGGTAACGAGCCGCGACGCGAACAGTTACGGCGGTGACAGCGCCTTCAATGAGAATGATTTCCAGGGCAAGCAACCCGGGCATTAGGAGAATGCGACCTCCACATGCAACGAAGAAGTTGCTACCGCTTCCTAGTAAGTATCTTACTGTTACTGTTTAGACTGTGAGATCCAGGTTAGCCCCAATCTATGAGTGCGTTCGTCGCGATAACAGGTTTCGGGCACCAATGGCTCGTCCAATCTGTGCGCCTATAGCATAATCCGTTACACAATATTATCAAACGCAGACGATTGTTCCGTCGGCAGCTAAGCCGCAATTCAAACTGCGACTGCTGGAAGGGCGTGGCTAGAAGATCAATACCCGGACTATGAATTGCGGGCGTTGTTCGTCTATTGCACACTCAACTAGTACTGTCCTTTGTCGAATAAGAGACTCCGACGCCCCGTTGACGCATATTACAGCAGACAGCCATCTGAGCTTAGGCTAACATAGAGACGAGCGAGCGACAGCGATCCGTGGTAGGTTGTGACAATTAGAATCGTAGTGTACATGTTTCTGCAGGCACACATAATTACATGTGCCACTATTATGGTTCCGCAAAGGAGGTACAGTCGAACCGGCAACTCCTGACGGCCTGCCTCGTGTGTGCAACCTCATAGTAGC";;
    $('#alignment_str').prop('value', example_msa).change()
}

function file_or_str() {
  var checkBox = document.getElementById("checkbox");
  // If the checkbox is checked, display the output text
  if (checkBox.checked == true){
    document.getElementById("alignment_file").disabled = false;
    document.getElementById("alignment_str").disabled = true;
    document.getElementById("alignment_str").value = '';
  } else {
    document.getElementById("alignment_file").disabled = true;
    document.getElementById("alignment_str").disabled = false;
    document.getElementById("alignment_file").value = '';
  }
}


function openAdvanced() {
    var x = document.getElementById("advanced");
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}

function validate_lib_file(){
    return true;
    var alternative_lib = document.getElementById("alternative_lib").value
    if (alternative_lib != '' && !(alternative_lib.toLowerCase().endsWith('json'))) {
        alternative_lib_file_name = alternative_lib.replace(/^.*[\\\/]/, '')
        alert("Reference library "+alternative_lib_file_name+" is illegal. Only json format is allowed.");
        return false;
    }
    return true;
}
function validate_read_files() {
    return true;
    var R1s = [document.getElementsByName("run1_R1")[0].value,
        document.getElementsByName("run2_R1")[0].value,
        document.getElementsByName("run3_R1")[0].value,
        document.getElementsByName("run4_R1")[0].value,
        document.getElementsByName("run5_R1")[0].value,
        document.getElementsByName("run6_R1")[0].value]
    var R2s = [document.getElementsByName("run1_R2")[0].value,
        document.getElementsByName("run2_R2")[0].value,
        document.getElementsByName("run3_R2")[0].value,
        document.getElementsByName("run4_R2")[0].value,
        document.getElementsByName("run5_R2")[0].value,
        document.getElementsByName("run6_R2")[0].value]

    for (i = 0; i < R1s.length; i++) {
        if (R1s[i] == '' && R2s[i] == ''){
            continue
        } else if (R1s[i] == '' && R2s[i] != '') {
            alert("R1 file of Replicate "+String(i+1)+" is missing (either you upload both of R1 and R2 or none).");
            return false;
        } else if (R1s[i] != '' && R2s[i] == '') {
            alert("R2 file of Replicate "+String(i+1)+" is missing (either you upload both of R1 and R2 or none).");
            return false;
        } else {
            if (!(R1s[i].endsWith('fastq') || R1s[i].endsWith('gz'))) {
                alert("R1 file Replicate "+String(i+1)+" is illegal. Only fastq and gzip formats are allowed.");
                return false;
            }
            if (!(R2s[i].endsWith('fastq') || R2s[i].endsWith('gz'))) {
                alert("R2 file Replicate "+String(i+1)+" is illegal. Only fastq and gzip formats are allowed.");
                return false;
            }
        }
    }
    return true;
}

function setDefaultMassSpecSeq(){
    var MMU = document.getElementsByName("MMU")[0].value;
    if (MMU === "mouse"){
        document.getElementById("mass_spec_seq").value = "AK";
    } else {
        document.getElementById("mass_spec_seq").value = "ASTK";
    }
}