function loadExample() {
    $('#checkbox').prop('checked', false).change()
    var example_msa=">Sp000\nTAAAGAGTTGCAAAACTCCCAA-ACCCTTTGTGAACCTTACC--AAA----GTTCGTTG-CTTCGGCAGGCGGCCCCAGGGCGGGGCC-TGCCAGCCCGGT---CTCTCC----ACCGGGTGCCTGCCGGGCGGAAA-CAAAA-CTCT-GTTATATTTAT-GTC-GTCTGAGCAACCAAAACAAATAA-TTAAAACTTTCAACAACGGATCTCTTGGTTCTGGCATCGATGAAGAACGCAGCGAAATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCACTAGTATTCTGGTGGGCATGCCTGTCCGAGCGTCATTTCAACCCTCAAGCCCTGTTTTGCTTGGTGTTGGGGCCCTGCC--GGAC-TCTTCC-GT-CCCGCAGGCCCCCAAGGACAGTGGCGGGCTCGCTAG-TGCTCCGAGCGTAGTAGCAATCGTTTTCTCGCTCAGGACGCCTCGCGGGTTCCC-GGCCGTAAAA-CCCCCTAAT----TTTTAC--AAGGG\n>Sp001\nTAAAGAGTTGTAAAACTCCCAA-ACCCTTTGTGAACCTTACC--AAA----GTTCGTTG-CTTCGGCAGGCGGCCCCAGGGCGGGGCC-TGCCAGCCCGGT---CTCTCC----ACTGGGTGCCTGCCGGGCGGAAA-CAAAA-CTCT-GTTATATTTAT-GTC-GTCTGAGCAATCAAAACAAATAA-TTAAAACTTTCAACAACGGATCTCTTGGTTCTGGCATCGATGAAGAACGCAGCGAAATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCACTAGTATTCTGGTGGGCATGCCTGTTCGAGCGTCATTTCAACCCTCAAGCCCTGTTTTGCTTGGTGTTGGGGCCCTGCC--GGAC-TCTTCT-GT-CCCGCAGGCCCCCAAGGACAGTGGCGGGCTCGCTAG-TGCTCCGAGCGTAGTAGCAATCGTTTTCTCGCTCAGGACGCCTCGCGGGTTCCC-GGCCGTAAAA-CCCCCTAAT----TTTTAC--AAGGG\n>Sp002\nTAAAGAGTTGCAAAACTCCCAA-ACCCTTTGTGAACCTTACC--AAA----GTTCGTTG-CTTCGGCAGGCGGCCCCAGGGCGGGGCC-TGCCAGCCCGGT---CTCTCC----ACCGGGTGCCTGCCGGGCGGAAA-CAAAA-CTCT-GTTATATTTAT-GTT-GTCTGAGCAACCAAAACAAATAA-TTAAAACTTTCAACAACGGATCTCTTGGTTCTGGCATCGATGAAGAACGCAGCGAAATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCACTAGTATTCTGGTGGGCATGCCTGTCCGAGCGTCATTTCAACCCTCAAGCCCTGTTTTGCTTGGTGTTGGGGCCCTGCC--GGAC-TCTTCC-GT-CCCGCAGGCCCCCAAGGACAGTGGCGGGCTCGCTAG-TGCTCCGAGCGTAGTAGCAATCGTTTTCTCGCTCAGGACGCCTCGCGGGTTCCC-GGCCGTAAAA-CCCCCTAAT----TTTTAC--AAGGG\n>Sp003\nTAAAGAGTTGCAAAACTCCCAAAACCCTATGTGAACCGTACC--AAA----GTTCGTTGCCTCTGGCAGGCGGCCCCAGGGCGGGGCC-TGCT-GCCCGGG---TCT-------CCCGGGTGCCTGCCGGCGGGATG-CAAAA-CTCT-GTATTATCTA--GCC-GTCTGAGCAACCAAAACAAATAA-TTAAAACTTTCAACAACGGATCTCTTGGTTCTGGCATCGATGAAGAACGCAGCGAAATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCACTAGTATTCTGGTGGGCATGCCTGTTCGAGCGTCATTTCAACCCTCAAGCCCAGTTT-GCTTGGTGTTGGGGCCCTGCC--GGACGTCCG--CGT-CCCGCAGGCCCCCAAGGACAGTGGCGGGCTCGCCAG-TGCTCCGAGCGTAGTAGCAATCGTTTTCTCGCTCAGGACGCGCGGCGGGTTCCC-GGCCGTTAAA-CCCCCAAAACA---TACAC--AAGGG\n>Sp004\nTAAAGAGTTGCAAAACTCCCAAAACCCTATGTGAACCGTACC--AAA----GTTCGTTGCCTCTGGCAGGCGGCCCCAGGGCGGGGCC-TGCT-GCCCGGG---TCT-------CCCGGGTGCCTGCCGGCGGGATG-CAAAA-CTCT-GTATTATCTA--GCC-GTCTGAGCAACCAAAACAAATAA-TTAAAACTTTCAACAACGGATCTCTTGGTTCTGGCATCGATGAAGAACGCAGCGAAATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCACTAGTATTCTGGTGGGCATGCCTGTTCGAGCGTCATTTCAACCCTCAAGCCCAGTTT-GCTTGGTGTTGGGGCCCTGCC--GGACGTCCG--CGT-CCCGCAGGCCCCCAAGGACAGTGGCGGGCTCGCCAG-TGCTCCGAGCGTAGTAGCAATCGTTTTCTCGCTCAGGACGCGCGGCGGGTTCCC-GGCCGTTAAA-CCCCCAAAACA---TACAC--AAGGG\n>Sp005\nTAAAGAGTTGCAAAACTCCCAAAACCCTTTGTGAACTGTACCCCAAAAAAAGTTCGTTG-CTTCGGTGGGCGGTCCCAGGGAGGGGCC-CCCG-GCCCGGGTCCTCGC---GGCCCCGGGCGCCTGCCGGGCGAGAG-CAAAAACTCT-GTTATTTTTTAAGTC-TTCTGAGCAACCAAAACAAATAA-TTAAAACTTTCAACAACGGATCTCTTGGTTCTGGCATCGATGAAGAACGCAGCGAAATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCACTAGTATTCTGGTGGGCATGCCTGTTCGAGCGTCATTTCAACCCTCAAGCCCTGTTT-GCTTGGTGTTGGGGCCCTGCCGCGGAC-TCACCC-GTCCCCGCAGGCCCTCAAGGTCAGTGGCGGGCTCGCTAG-TGCTCCGAGCGTAGTAGCAATCGTTTTCTCGCTCAGGACGTACGGCGGGTTCCC-GGCCGTAAAA-CCCCCCAAA-----TTTACCAAAGGG\n>Sp006\nTAAAGAGTTGCAAAACTCCCAAAACCCTTTGTGAACTGTACCCCAAAAAAAGTTCGTTG-CTTCGGTGGGCGGCCCCAGGGAGGGGCC-CCCG-GCCCGGGTCCTCGC---GGCCCCGGGCGCCTGCCGGGCGAGAG-CAAAAACTCT-GTTATTTTTTAAGTC-TTCTGAGCAACCAAAACAAATAA-TTAAAACTTTCAACAACGGATCTCTTGGTTCTGGCATCGATGAAGAACGCAGCGAAATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCACTAGTATTCTGGTGGGCATGCCTGTTCGAGCGTCATTTCAACCCTCAAGCCCTGTTT-GCTTGGTGTTGGGGCCCTGCCGCGGAC-TCACCC-GTCCCCGCAGGCCCTCAAGGTCAGTGGCGGGCTCGCTAG-TGCTCCGAGCGTAGTAGCAATCGTTTTCTCGCTCAGGACGTACGGCGGGTTCCC-GGCCGTAAAA-CCCCCCAAA-----TTTACCAAAGGG\n>Sp007\nTAAAGAGTTGCAAAACTCCCAAAACCCTTTGTGAACTGTACCCCAAAAAAAGTTCGTTG-CTTCGGAGGGCGGCCCCAGGGAGGGGCC-CCCG-GCCCGGGTCCTCGC---GGCCCCGGGCGCCTGCCGGGCGAGAG-CAAAAACTCT-GTTATTTTTTAAGTC-TTCTGAGCAACCAAAACAAATAA-TTAAAACTTTCAACAACGGATCTCTTGGTTCTGGCATCGATGAAGAACGCAGCGAAATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCACTAGTATTCTGGTGGGCATGCCTGTTCGAGCGTCATTTCAACCCTCAAGCCCTGTTT-GCTTGGTGTTGGGGCCCTGCCGCGGAC-TCACCC-GTCCCCGCAGGCCCTCAAGGTCAGTGGCGGGCTCGCTAG-TGCTCCGAGCGTAGTAGCAATCGTTTTCTCGCTCAGGACGTACGGCGGGTTCCC-GGCCGTAAAA-CCCCCCAAA-----TTTACCAAAGGG";;
    $('#alignment_str').prop('value', example_msa).change()
}

function fileOrStr() {
  var loadFile = document.getElementById("checkbox");
  // If the loadFile checkbox is checked, display the output text
  if (loadFile.checked == true){
    document.getElementById("alignment_file").disabled = false;
    document.getElementById("alignment_str").disabled = true;
    document.getElementById("alignment_str").value = '';
  } else {
    document.getElementById("alignment_file").disabled = true;
    document.getElementById("alignment_str").disabled = false;
    document.getElementById("alignment_file").value = '';
    document.getElementById("running_mode_0").checked = true;
    getUserDefinedTopology();
  }
}

function getUserDefinedTopology() {
  var radio = document.getElementById("running_mode_2");
  // If this option is set, display the upload topology window
  if (radio.checked == true){
    document.getElementById("user_defined_topology").disabled = false;
    document.getElementById("user_defined_topology").value = '';
    document.getElementById("user_defined_topology_block").style.display = 'block';
  } else {
    document.getElementById("user_defined_topology").disabled = true;
    document.getElementById("user_defined_topology").value = '';
    document.getElementById("user_defined_topology_block").style.display = 'none';
  }
}

function validateFields(){
    var loadFile = document.getElementById("checkbox");
    var fileAlignment = document.getElementById("alignment_file");
    var txtAlignment = document.getElementById("alignment_str");
    if ((loadFile.checked == true && fileAlignment.value == '') ||
       (loadFile.checked == false && txtAlignment.value == '')){
        alert("No multiple sequence alignment was provided.");
        return false;
    }

    var radio0 = document.getElementById("running_mode_0");
    var radio1 = document.getElementById("running_mode_1");
    var radio2 = document.getElementById("running_mode_2");
    if (radio0.checked == false && radio1.checked == false && radio2.checked == false){
        alert("Please choose a running mode.");
        return false;
    }

    var userDefinedTree = document.getElementById("user_defined_topology");
    if (radio2.checked == true && userDefinedTree.value == ''){
        alert("No user-defined topology was provided. Please provide a topology or choose a different running mode.");
        return false;
    }
    return true;
}
